export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const CAPNHAT_PROFILE_REQUEST = 'CAPNHAT_PROFILE_REQUEST';
export const CAPNHAT_PROFILE_SUCCESS = 'CAPNHAT_PROFILE_SUCCESS';
export const CAPNHAT_PROFILE_FAIL = 'CAPNHAT_PROFILE_FAIL';
export const CAPNHAT_PROFILE_RESET = 'CAPNHAT_PROFILE_RESET';